kind: live
title: sdnext

defaults:
  life_span: 5d

volumes:
  models:
    remote: storage:$[[ flow.project_id ]]/models
    mount: /mnt/models
    local: models
  data:
    remote: storage:$[[ flow.project_id ]]/data
    mount: /mnt/data
    local: data

jobs:
  stablediffusion:
    image: vladmandic/sdnext-cuda:latest
    name: stablediffusion
    preset: gpu-medium
    http_port: "7860"
    browse: true
    env:
      SD_LORA_DEBUG: true
      COMMANDLINE_ARGS: --docs --cors-origins=* --use-cuda --debug --listen --insecure
      HUGGING_FACE_HUB_TOKEN: secret:HF_TOKEN
    volumes:
      - ${{ volumes.models.ref_rw }}
      - ${{ volumes.data.ref_rw }}
